@startuml room manager
left to right direction
actor Player as P
actor Questioner as Q
actor Guesser as G
P -|> Q
P -|> G

rectangle "Game Manager" as GM {
    (役職を決める) as assign
    (お題を出す) as theme
    P --> assign 
    Q -> theme

    rectangle loop {
        (質問をする) as ask
        (質問に答える) as answer

        G --> ask
        Q --> answer
    }

    note top of loop
        答えが出たらゲーム終了
    end note
}

@enduml